### ISSUE TITLE
QuickCRM module file permission issue

### ISSUE THREAD

**Issue by crcjwice123** [bitnami/bitnami-docker-suitecrm#95] opened 2018-11-22 09:06 UTC
**Description**
After installing QuickCRM V3.9.0 module, following error occurs:

> FILE PERMISSIONS ARE NOT SET PROPERLY IN custom/QuickCRM.
> PLEASE SET PERMISSIONS 
> - FOR ALL FILES IN custom/QuickCRM FOLDER AND SUBFOLDERS SIMILAR TO config.php
> - FOR custom/QuickCRM FOLDER AND SUBFOLDERS SIMILAR TO cache FOLDER
> 
> You can access the CRM from a mobile at 
>  - Web app : http://127.0.0.1//mobile
>  - QuickCRM for iOS : http://127.0.0.1/
>  - QuickCRM for Android : http://127.0.0.1/

Then I get into the container and run commands

> find custom/QuickCRM -type f -exec chmod 644 {} \;
> find custom/QuickCRM -type d -exec chmod 755 {} \;

but http://localhost:80/mobile still shows 404 NOT FOUND

**Steps to reproduce the issue:**

1. start suitecrm container
2. download QuickCRM zip from
 https://github.com/QuickCRM/QuickCRM-Basic/files/2209701/QuickCRM-Mobile-Basic-3.9.0.zip
3. log in suitecrm, install QuickCRM module 
4. permission error pops up after installation, get into container and change file/folder permission
5. in suitecrm setting, click QuickCRM Update
6. go to http://localhost:80/mobile but stills shows 404

**Describe the results you received:**

**Describe the results you expected:**
http://localhost:80/mobile shows content and mobile app can connect to local suitecrm.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 18.09.0, build 4d60db4 
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d380109
ID: N3Y3:UTTF:OOWK:AUWQ:MP7Q:3VZQ:IF2X:GCM3:5P73:UFON:VN2D:Q2OF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 66
 System Time: 2018-11-22T09:04:49.2162268Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://cficc3x3.mirror.aliyuncs.com/
Live Restore Enabled: false
Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
`Docker for windows`

**Comment by marcosbc** [comment] 2018-11-22 16:01
Hi, just wanted to let you know that we're looking into this and will get back to you once we have any update.

**Comment by marcosbc** [comment] 2018-11-23 13:33
Hi @crcjwice123, after some investigation, we see this is happening due to files not being found in /bitnami/suitecrm. The issue is not all the SuiteCRM files are being persisted.

We have already seen this in https://github.com/bitnami/bitnami-docker-suitecrm/issues/78 and are working on fixing this, expecting it to be released soon.

However, please note that the new release will break backward compatibility with previous container versions (meaning you would not be able to upgrade the container only by pulling the new image), due to changing the list of SuiteCRM directories being persisted.

**Comment by crcjwice123** [comment] 2018-11-23 14:07
Thanks a lot for fixing this! 

Does "break backward compatibility" mean I have to delete the old suitecrm volume before start new container?

**Comment by marcosbc** [comment] 2018-11-23 16:12
@crcjwice123 Yes, that's right. However, in the meantime, if you hardcode the exact release of the container (e.g. `7.10.10-debian-9-r17` or previous releases), you can keep the old installation running in the meantime until you are ready to migrate to the newer release.

**Comment by marcosbc** [comment] 2018-11-27 09:14
Hi @crcjwice123, we released the following SuiteCRM container releases, which implements the changes we mentioned in previous comments:

- **7.10.10-debian-9-r19**
- **7.10.10-ol-7-r26**

We also updated the [README](https://github.com/bitnami/bitnami-docker-suitecrm/#upgrade-this-application) to reflect these changes.

I'm going to describe below how to migrate previous releases of the container to the newest release. Please let us know if you find any issues.

____

In order to **migrate** from previous releases (7.10.10-debian-9-r19, 7.10.10-ol-7-r23 or prior releases) please follow these steps:

- Create backups in case something goes wrong:

  * SuiteCRM container: Backup all persist data located at `/bitnami/suitecrm`.
  * MariaDB database: [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of SuiteCRM's database.

- Start a new SuiteCRM container. You might need to specify a different port configuration in order to have both the current (with the new changes) and previous container release (without them) running. Ensure docker-compose is creating a different container, with different volumes.

- Migrate SuiteCRM `htdocs` directory:

  * Inside the original SuiteCRM container, compress the entire SuiteCRM folder, following any symlink and creating the ".initialized" (so it has the same format as newer releases of the container):

        cd /opt/bitnami/suitecrm
        tar czfh /tmp/suitecrm-htdocs.tar.gz .

  * Copy the compressed tarball to the outside of the container (supposing below its id is 0123456789ab):

        docker cp 0123456789ab:/tmp/suitecrm-htdocs.tar.gz .

  * Copy that tarball to the new SuiteCRM container, which includes the new changes (supposing below its id is abcdef012345): 

        docker cp suitecrm-htdocs.tar.gz abcdef012345:/tmp

  * Inside the new SuiteCRM container, with the new changes, replace `/bitnami/suitecrm` with the contents of the tarball:

        rm -rf /bitnami/suitecrm/*
        tar xzf /tmp/suitecrm-htdocs.tar.gz -C /bitnami/suitecrm

- Restore the MariaDB database:

  * [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of the old MariaDB database container (supposing below its id is 54321abcdef):

        docker exec 012345abcdef mysqldump -u root bitnami_suitecrm > suitecrm-db.sql

  * Copy the backup to the new MariaDB container (supposing its id is fedcba012345):

        docker cp suitecrm-db.sql fedcba012345:/tmp

* [Restore the backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/), inside the new MariaDB database container:

        mysql -u root bitnami_suitecrm < /tmp/suitecrm-db.sql

* Stop the old SuiteCRM and MariaDB container (using the old `docker-compose.yml` file).
* Restart the new SuiteCRM and MariaDB container (using the new `docker-compose.yml` file).

**Comment by crcjwice123** [comment] 2018-11-29 07:50
Now I can successfully connect to quickCRM! Thanks so much for your efforts!
BTW why the data is stored separately in both /bitnami/suitecrm and mariaDB? Because in normal cases, application data is stored only in mariadb.

**Comment by marcosbc** [comment] 2018-11-29 10:11
@crcjwice123 I'm really glad to hear that!

Regarding the data question, SuiteCRM stores application data such as plugin code, extensions, themes and other data in the file system, not in the database.
Therefore, any changes you performed to your SuiteCRM install will remain there when you recreate the container (but keeping the volume).

I'm closing this issue as it has been resolved on your side.

**Closed by marcosbc** 2018-11-29 10:11 UTC
