### ISSUE TITLE
Inbound Email cannot function without the IMAP c-client libraries enabled/compiled with the PHP module.

### ISSUE THREAD

**Issue by sguilly** [bitnami/bitnami-docker-suitecrm#35] opened 2017-01-25 15:23 UTC
Issue to create a inbound email : 'Admin -> Inbound Email'

Inbound Email cannot function without the IMAP c-client libraries enabled/compiled with the PHP module. Please contact your administrator to resolve this issue.

**Comment by sguilly** [comment] 2017-01-25 16:08
imap.so seems to be present in extension folder
but when i try to enable it in php.ini with "extension=imap.so"
the container exist with :

suitecrm_1  | nami    ERROR Unable to start com.bitnami.apache: [Wed Jan 25 16:01:55.177064 2017] [so:warn] [pid 53] AH01574: module rewrite_module is already loaded, skipping
suitecrm_1  | 
bitnamidockersuitecrm_suitecrm_1 exited with code 0

**Comment by juan131** [comment] 2017-02-16 16:49
@sguilly I am able to reproduce the issue. The problem seems to be that the extension is enabled by default. I could workaround it following these steps:

 - Adding the line below at the bottom of the configuration file `/opt/bitnami/php/conf/php.ini`:

```
extension = imap.so
```

 - Restarting Apache running the command:

```
nami restart apache
```

We are working on fixing it for future releases.

**Comment by proffalken** [comment] 2017-03-21 23:55
Hi, do you have a date for when this will be in the release, or advice on how to update the container as described above please?

**Comment by dbarranco** [comment] 2017-05-24 14:26
Hi @proffalken 

I'm so sorry for the delay in answering this issue. I would like to inform you that we've just released a new revision of the module adding this extension by default.

I'm going to close this issue, please, do not hesitate on re-open it if you find any other similar issue.

Just executing:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-suitecrm/master/docker-compose.yml
$ docker-compose up
```

Should be enough to get the latest version.


Thank you so much. Best regards!

**Closed by dbarranco** 2017-05-24 14:26 UTC
