### ISSUE TITLE
Install Language pack - Error Could not copy file

### ISSUE THREAD

**Issue by leandro-correia** [bitnami/bitnami-docker-suitecrm#54] opened 2017-04-10 16:30 UTC
I tried to install the  pt_BR Language pack and got this error on commit installation:

> Could not copy file cache/upgrades/temp/P1MDgE/./upgrade/scripts/pt_BR.lang.php to /opt/bitnami/suitecrm/./upgrade/scripts/pt_BR.lang.php

After changing permission on container folder '/opt/bitnami/suitecrm/' to 777, the installation worked.

Am I doing something wrong? I used the default docker-compose.yml.

Ubuntu 16.04
Docker version 1.13.1, build 092cba3
BITNAMI IMAGE 7.8.2-r1

Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.549 GiB
Name: falcon346
ID: XRWH:5YZG:VIHC:XAKT:VTZ3:ABMV:RW23:HU4I:MDNC:PRM7:KN57:OG63
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by juan131** [comment] 2017-04-11 11:00
> After changing permission on container folder '/opt/bitnami/suitecrm/' to 777, the installation worked.

This is very insecure and I don't recommend you to do so. The problem seems to be related with the user "daemon" which doesn't have permissions on certain folders. 

Could you please describe the whole process you followed in order to install the Portuguese translation so we can reproduce it? Once we reproduce it we would identify which specific directories are affected for the permissions issue and we'll be able to find the best solution.

**Comment by leandro-correia** [comment] 2017-04-13 12:59
Hello @juan131

I used the default docker-compose.yml and after everything was running, I just followed the instructions from this link (https://sites.google.com/site/translatingsuitecrm/faq/install_language) to install pt_BR language.

When I hit “Commit” button, the problem happens. I tried several times, same message everytime.

If you require any further information, please do not hesitate to contact me.

**Comment by dgonzalezruiz** [comment] 2017-04-14 15:32
Hi @leandro-correia ,

Thanks for reporting this issue to us. I have corrected the issue reported, and the changes will be made effective soon, so just pulling again when the image is updated should be enough. 

Please do not hesitate to request more help if you encountered any other issue.

Best regards,

David González

**Comment by sameersbn** [comment] 2017-04-27 06:49
@leandro-correia can you please confirm if the issue has been resolved after upgrading to the `7.8.3-r1` release?

**Comment by dbarranco** [comment] 2017-05-16 08:36
Since this issue hasn't been reported more I'm proceeding to close it. 
@leandro-correia feel free to open it again if you find any error related to this.

Best regards.

**Closed by dbarranco** 2017-05-16 08:36 UTC
