### ISSUE TITLE
Mariadb volume data dir needs 777 to work

### ISSUE THREAD

**Issue by RobinEd** [bitnami/bitnami-docker-suitecrm#72] opened 2018-01-04 10:32 UTC
if you want a persistent database outside of the docker image, /var/lib/docker/volumes/mariadb_data/_data/ needs to be 777! Otherwise you get the following error when bringing the container up:
mariadb_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'

**Steps to reproduce the issue:**
NB running as a system user, not as root user!

1. create volume
docker volume create --label mariadb_data --name mariadb_data
2. docker-compose.yml
```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```
3. docker-compose up

**Describe the results you received:**

mariadb_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb'

the mariadb image goes up without an error

**Additional information you deem important (e.g. issue happens only occasionally):**

chmod 777 /var/lib/docker/volumes/mariadb_data/_data/

then the docker image will go up

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 0
Server Version: 17.11.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797GiB
Name: suitecrm.edgarbv.int
ID: XMMD:ADXC:EDOO:7XP5:5GCD:IBKQ:TK4X:NQDW:Y27A:MNKF:I5NC:NODW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.6.1
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
This is running on CentOS 7 64 bit in a vmware esxi 6.5 VM

**Comment by dbarranco** [comment] 2018-01-05 10:50
Hi @RobinEd 

I am afraid that you can not set a full path in the volume unless you have changed the owner/permissions of that directory. This is not an issue of the Bitnami images, it's the default behaviour of Docker. You have more information about that [here](https://github.com/moby/moby/issues/2259).

But if your intention is to have in `/var/lib/docker/volumes/whatever` the persistent volumes of your containers you can use this:

* Create the volumes: 
`docker volume create --label mariadb_data --name mariadb_data`
`docker volume create --label suitecrm_data --name suitecrm_data`

* Reference those volumes as `external` drivers in your docker-compose:

```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - suitecrm-tier
    environment:
      - MARIADB_ROOT_PASSWORD= ag63hxfd44SS3h66
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'suitecrm_data:/bitnami'
    networks:
      - suitecrm-tier
    environment:
      - MARIADB_PASSWORD= ag63hxfd44SS3h66

volumes:
  mariadb_data:
    external:
      name: mariadb_data
  suitecrm_data:
    external:
      name: suitecrm_data
```

In that way, the volumes that are created won't follow the naming convention of docker-compose (using as prefix the folder in which you have the docker-compose, [information about that here](https://forums.docker.com/t/docker-compose-prepends-directory-name-to-named-volumes/32835/4)) and will use the ones you have created:

```
bitnami@ ~ () $ docker volume ls
DRIVER              VOLUME NAME
local               mariadb_data
local               suitecrm_data
```

Also, if you inspect the container once deployed to see where are the volumes mounted with `docker inspect bitnami_mariadb_1`, you will see the following:

```
"Mounts": [
            {
                "Type": "volume",
                "Name": "mariadb_data",
                "Source": "/var/lib/docker/volumes/mariadb_data/_data",
                "Destination": "/bitnami",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
```

So it has the correct path that you want. The folder `_data` is automatically created by Docker.


May this be what you are looking for? 

Best regards.

**Comment by RobinEd** [comment] 2018-01-05 11:43
Thanks for the explanation! I am puzzled though why giving the full path does work for the suitecrm volume - I don't need to change permissions there?

**Comment by sameersbn** [comment] 2018-01-05 12:27
@RobinEd Please update you're docker-compose.yml to

```yaml
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  fix-mariadb-permissions:
    image: 'bitnami/mariadb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
    depends_on:
      - fix-mariadb-permissions
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```

The issue is, the bitnami/mariadb image now uses a non-root approach to start processes in a container. This is done to enhance the security. But unfortunately a side effect of this is that we're no longer able to correct any file permission issues automatically, thereby requiring users to explicitly set the ownership of the data volume.

The above workaround basically is another take at this required manual step while using host mounted volumes to fix the ownership of the data volume.

**Comment by sameersbn** [comment] 2018-01-05 12:28
ps. I would advise against mounting your volume from `/var/lib/docker/`

**Comment by dbarranco** [comment] 2018-01-05 12:28
Hi @RobinEd 

The SuiteCRM container won't fail because the user that is running the installer of SuiteCRM is `root`. In the MariaDB container, we changed this approach to not to user the `root` user as the default user in the container, for security concerns. [Changelog including the change of approach](https://github.com/bitnami/bitnami-docker-mariadb#10128-r2).

Indeed, you could use the previous docker-compose you shared but adding the `user: root` key:

```
version: '2'

networks:
  suitecrm-tier:
    driver: bridge

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    user: root
    environment:
      - MARIADB_ROOT_PASSWORD=ag63hxfd44SS3h66
    volumes:
      - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
    networks:
      - suitecrm-tier
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_PASSWORD=ag63hxfd44SS3h66
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/lib/docker/volumes/suitecrm_data/_data:/bitnami'
    networks:
      - suitecrm-tier
```

And this would work, and you will also have the volume name you're looking for:

```
bitnami@ ~ () $ docker volume ls
DRIVER              VOLUME NAME
local               bitnami_suitecrm_data
local               mariadb_data
```

So it seems Docker admit full path to the volumes, that's my mistake, sorry.

So you can now choose which is the best approach for you, having the container executed by root or the non-root approach. 
Best regards.

**Comment by dbarranco** [comment] 2018-01-05 12:29
@sameersbn Wouldn't that be the same result that leaving the name of the volume? 
Inspecting the containers they end up having mounted the same folder 🤔

**Comment by sameersbn** [comment] 2018-01-05 12:34
@dbarranco I would expect it to have the same result as they are the same folder. Maybe user is mounting the wrong path. Any which ways, I will simulate this scenario to learn more.

**Comment by dbarranco** [comment] 2018-01-05 12:41
From my tests it was the same at the end, but any user can mess that easily.
It's quite interesting the docker-compose with the external drivers and the permissions that it has :D

**Comment by sameersbn** [comment] 2018-01-05 15:37
yea, I see its super weird that volumes created by `docker volume create` and one's created by `docker-compose up` seem to bear different characteristics.

**Comment by sameersbn** [comment] 2018-01-05 15:39
@RobinEd could you confirm the fix worked in your use case?

**Comment by RobinEd** [comment] 2018-01-12 09:27
Hi, @sameersbn your method seems to work, but doesn't create a database.

[user@suitecrm ~]$ docker-compose up
Pulling fix-mariadb-permissions (bitnami/mariadb:latest)...
latest: Pulling from bitnami/mariadb
21a7e111de8c: Already exists
65e50e28a4a4: Already exists
b94a89aafdb1: Already exists
7487ef2491c8: Already exists
fbabf81a333a: Already exists
f532281efb89: Already exists
fe9e6da83046: Pull complete
9198bc632af9: Pull complete
b766f87309cd: Pull complete
Digest: sha256:41204a6314129a9747a4e8378c7dc28e7d6bfda1e9031f0aa280a422d39a3918
Status: Downloaded newer image for bitnami/mariadb:latest
Creating razor_fix-mariadb-permissions_1 ... 
Creating razor_fix-mariadb-permissions_1 ... done
Creating razor_mariadb_1 ... 
Creating razor_mariadb_1 ... done
Recreating razor_suitecrm_1 ... 
Recreating razor_suitecrm_1 ... done
Attaching to razor_fix-mariadb-permissions_1, razor_mariadb_1, razor_suitecrm_1
fix-mariadb-permissions_1  | 
fix-mariadb-permissions_1  | Welcome to the Bitnami mariadb container
fix-mariadb-permissions_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
fix-mariadb-permissions_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
fix-mariadb-permissions_1  | Send us your feedback at containers@bitnami.com
fix-mariadb-permissions_1  | 
mariadb_1                  | 
mariadb_1                  | Welcome to the Bitnami mariadb container
mariadb_1                  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1                  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1                  | Send us your feedback at containers@bitnami.com
mariadb_1                  | 
suitecrm_1                 | 
suitecrm_1                 | Welcome to the Bitnami suitecrm container
suitecrm_1                 | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm_1                 | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm_1                 | Send us your feedback at containers@bitnami.com
suitecrm_1                 | 
razor_fix-mariadb-permissions_1 exited with code 0
mariadb_1                  | nami    INFO  Initializing mariadb
mariadb_1                  | mariadb INFO  ==> Cleaning data dir...
mariadb_1                  | mariadb INFO  ==> Configuring permissions...
mariadb_1                  | mariadb INFO  ==> Validating inputs...
mariadb_1                  | mariadb INFO  ==> Initializing database...
suitecrm_1                 | nami    INFO  Initializing apache
suitecrm_1                 | apache  INFO  ==> Reconfiguring PID file location...
suitecrm_1                 | nami    INFO  apache successfully initialized
suitecrm_1                 | nami    INFO  Initializing php
suitecrm_1                 | nami    INFO  php successfully initialized
suitecrm_1                 | nami    INFO  Initializing suitecrm
mariadb_1                  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
suitecrm_1                 | suitecr INFO  suitecrm has being already initialized, restoring...
mariadb_1                  | mariadb INFO  ==> Enabling remote connections...
mariadb_1                  | mariadb INFO 
mariadb_1                  | mariadb INFO  ########################################################################
mariadb_1                  | mariadb INFO   Installation parameters for mariadb:
mariadb_1                  | mariadb INFO     Root User: root
mariadb_1                  | mariadb INFO     Root Password: **********
mariadb_1                  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1                  | mariadb INFO  ########################################################################
mariadb_1                  | mariadb INFO 
mariadb_1                  | nami    INFO  mariadb successfully initialized
mariadb_1                  | INFO  ==> Starting mariadb... 
mariadb_1                  | INFO  ==> Starting mysqld_safe...
mariadb_1                  | 180112 09:18:56 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1                  | 180112 09:18:56 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
suitecrm_1                 | suitecr INFO  Setting extra configuration...
suitecrm_1                 | suitecr INFO  Cleaning up folders..
suitecrm_1                 | suitecr INFO  Configuring Cron Jobs...
suitecrm_1                 | suitecr INFO  Configuring permissions...
suitecrm_1                 | suitecr INFO 
suitecrm_1                 | suitecr INFO  ########################################################################
suitecrm_1                 | suitecr INFO   Installation parameters for suitecrm:
suitecrm_1                 | suitecr INFO     Persisted data and properties have been restored.
suitecrm_1                 | suitecr INFO     Any input specified will not take effect.
suitecrm_1                 | suitecr INFO   This installation requires no credentials.
suitecrm_1                 | suitecr INFO  ########################################################################
suitecrm_1                 | suitecr INFO 
suitecrm_1                 | nami    INFO  suitecrm successfully initialized
suitecrm_1                 | INFO  ==> Starting suitecrm... 
suitecrm_1                 | 
suitecrm_1                 | 192.168.0.68 - - [12/Jan/2018:09:19:24 +0000] "GET / HTTP/1.1" 301 -
suitecrm_1                 | 192.168.0.68 - - [12/Jan/2018:09:19:25 +0000] "GET /index.php?action=Login&module=Users HTTP/1.1" 200 3825

BUT 

docker exec -it user_mariadb_1 /bin/bash
I have no name!@bbd9cae2e4f1:/$ mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.30-MariaDB Source distribution

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
+--------------------+
3 rows in set (0.00 sec)

**Comment by dbarranco** [comment] 2018-01-12 14:08
Hi @RobinEd 

That is happening because SuiteCRM has been previously initialised. As you can see in the logs:

```
suitecrm_1 | suitecr INFO suitecrm has being already initialized, restoring...
```

At the restore time, the container won't create another database as it expects one database created previously.
If you change the folder you are currently using to persist data of SuiteCRM (or if you create a backup of the current folder and then delete the folder) you will notice how SuiteCRM creates a database and the container works as expected.
Then you can restore in the persistence folder any other data you had in the previously folder.

Hope this clarify things.
Kind regards.

**Comment by RobinEd** [comment] 2018-01-18 10:37
Correct. After purging all the containers, networks, images, etc and rebuilding from scratch it did properly populate the database and create the files with permissions for user 1001 (whoever that is)

[root@suitecrm ~]#  ls -lah /var/lib/docker/volumes/
total 24K
drwx------.  4 root root  66 Jan 18 11:25 .
drwx--x--x. 14 root root 183 Dec  5 15:50 ..
drwxr-xr-x.  3 root root  19 Jan 12 10:18 mariadb_data
-rw-------.  1 root root 32K Jan 18 11:25 metadata.db
drwxr-xr-x.  3 root root  19 Jan 18 11:25 suitecrm_data
[root@suitecrm ~]#  ls -lah /var/lib/docker/volumes/mariadb_data/
total 0
drwxr-xr-x. 3 root root 19 Jan 12 10:18 .
drwx------. 4 root root 66 Jan 18 11:25 ..
drwxr-xr-x. 3 1001 1001 21 Jan 12 10:18 _data
[root@suitecrm ~]#  ls -lah /var/lib/docker/volumes/mariadb_data/_data/
total 0
drwxr-xr-x. 3 1001 1001 21 Jan 12 10:18 .
drwxr-xr-x. 3 root root 19 Jan 12 10:18 ..
drwxr-xr-x. 4 1001 1001 67 Jan 18 11:28 mariadb
[root@suitecrm ~]#  ls -lah /var/lib/docker/volumes/mariadb_data/_data/mariadb/
total 0
drwxr-xr-x. 4 1001 1001  67 Jan 18 11:28 .
drwxr-xr-x. 3 1001 1001  21 Jan 12 10:18 ..
drwxr-xr-x. 2 1001 1001  20 Jan 12 10:18 conf
drwxr-xr-x. 5 1001 1001 210 Jan 18 11:32 data
-rw-r--r--. 1 1001 1001   0 Jan 12 10:18 .initialized
-rw-r--r--. 1 1001 1001   0 Jan 18 11:28 .restored
[root@suitecrm ~]#  ls -lah /var/lib/docker/volumes/mariadb_data/_data/mariadb/data/
total 173M
drwxr-xr-x. 5 1001 1001  210 Jan 18 11:32 .
drwxr-xr-x. 4 1001 1001   67 Jan 18 11:28 ..
-rw-rw----. 1 1001 1001  16K Jan 12 10:18 aria_log.00000001
-rw-rw----. 1 1001 1001   52 Jan 12 10:18 aria_log_control
drwx------. 2 1001 1001  16K Jan 18 11:28 bitnami_suitecrm
-rw-rw----. 1 1001 1001  76M Jan 18 11:36 ibdata1
-rw-rw----. 1 1001 1001  48M Jan 18 11:36 ib_logfile0
-rw-rw----. 1 1001 1001  48M Jan 12 10:18 ib_logfile1
-rw-rw----. 1 1001 1001    0 Jan 12 10:18 multi-master.info
drwxr-xr-x. 2 1001 1001 4.0K Jan 12 10:18 mysql
drwxr-xr-x. 2 1001 1001   20 Jan 12 10:18 performance_schema
-rw-rw----. 1 1001 1001  24K Jan 18 11:32 tc.log

**Comment by dbarranco** [comment] 2018-01-19 08:51
Hi @RobinEd 

Thank you for confirming this.
As we consider this issue is solved we proceed to close it. Do not hesitate on opening more issues if you have any other questions or is there anything you do not understand, we will be more than happy to help you.

Kind regards.

**Closed by dbarranco** 2018-01-19 08:51 UTC
