### ISSUE TITLE
Export 500 Internal Error

### ISSUE THREAD

**Issue by lmorroni** [bitnami/bitnami-docker-suitecrm#83] opened 2018-04-12 16:31 UTC
Hello,
I noticed that exporting anything on my instance of SuiteCRM caused a 500 internal error.  I tried many things including permissions.  I think did a fresh install with the latest version here 7.10.4-r0 and I did a test where I added a lead and did an export of one lead and I received a 500 error.  Seems like a bug to me.
Larry

**Comment by juan131** [comment] 2018-04-13 10:19
Hi @lmorroni 

- Are you using the `docker-compose.yaml` to deploy you containers?
- Could you please share the error you obtain on the Apache Error log? You can find it under **/opt/bitnami/apache/logs/error_log**.
- 
- What exactly steps did you follow in order to export data? Could you please specify step-by-step so I can reproduce the same scenario?

**Comment by lmorroni** [comment] 2018-05-16 15:13
Sorry for the delay.  Yes, I have tried this using the standard docker-compose.yml file.  Clean volumes, images, etc.  Here's the error message:

````
[Wed May 16 15:12:49.109401 2018] [:error] [pid 149] [client 172.18.0.1:32782] PHP Warning:  require_once(export.php): failed to open stream: No such file or directory in /bitnami/suitecrm/include/MVC/Controller/SugarController.php on line 1014
[Wed May 16 15:12:49.109463 2018] [:error] [pid 149] [client 172.18.0.1:32782] PHP Fatal error:  require_once(): Failed opening required 'export.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/include/MVC/Controller/SugarController.php on line 1014
````

**Comment by lmorroni** [comment] 2018-05-16 15:26
Once you pointed me to this error log, I was able to figure out that it's a path issue.  Not sure why the path is not set properly but I did this inside the container and it now works
````
ln -s  /opt/bitnami/suitecrm/export.php /bitnami/suitecrm/export.php
````

**Comment by juan131** [comment] 2018-05-17 08:10
Hi @lmorroni 

That's very weird, I just created a new SuiteCRM container using the latest version of SuiteCRM (7.10.4-r18) and I could reproduce the issue. The problem is on the configuration file **/bitnami/suitecrm/include/MVC/Controller/entry_point_registry.php** has the following line:

```
'export' => array('file' => 'export.php', 'auth' => true),
```

It should be:

```
'export' => array('file' => '/opt/bitnami/suitecrm/export.php', 'auth' => true),
```

I will create a task to fix it asap. Thanks for reporting it.

**Comment by juan131** [comment] 2018-05-17 10:29
Hi @lmorroni I just released a new revision of the image fixing this issue, please take a look to **7.10.4-r19**

Please feel free to use and close the issue if you consider it solved

**Comment by lmorroni** [comment] 2018-05-17 12:58
I just confirmed that it is indeed now working.  Thanks for fixing it!
Larry

**Closed** 2018-05-17 12:58 UTC

**Comment by selckin** [comment] 2018-06-04 09:35
Using latest, and hitting the same problem, could it be broken again?

**Comment by juan131** [comment] 2018-06-04 09:53
Hi @selckin 

I was unable to reproduce it using the latest version of SuiteCRM. Could you please specify what version are you using?

I just checked it using the version **bitnami/suitecrm:7.10.4-r28**
